import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: "ZEROBASE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={` antialiased`}
      >
        {children}
        <Toaster position="top-center" richColors />

      </body>
    </html>
  );
}
